export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const FETCH_USER ='FETCH_USER'
export const FETCH_FAILED= 'FETCH_FAILED'

export const SINGUP_REQUEST = 'SINGUP_REQUEST'
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS'
export const SINGUP_FAILURE = 'SINGUP_FAILURE'

export const FETCH_USERS = 'FETCH_USERS'
export const ADUC_USER = 'ADUC_USER'
export const EDITEAZA_USER ='EDITEAZA_USER'

export const FETCH_PROFILES = 'FETCH_PROFILES'
export const SHOW_PROFILE = 'SHOW_PROFILE'

export const FAIL = 'FAIL'


export const PLATESTE = 'PLATESTE'
export const FETCH_PLATI= 'FETCH_PLATI'

export const ADAUGA_PROGRAM = 'ADAUGA_PROGRAM'
export const DELETE_PROGRAM = 'DELETE_PROGRAM'
export const FETCH_PROGRAMS = 'FETCH_PROGRAMS'

export const ADAUGA_PRETURI = 'ADAUGA_PRETURI'
export const DELETE_PRETURI = 'DELETE_PRETURI'
export const FETCH_PRETURI = 'FETCH_PRETURI'

export const ADAUGA_VIDEO = 'ADAUGA_VIDEO'
export const DELETE_VIDEO = 'DELETE_VIDEO'
export const FETCH_VIDEO = 'FETCH_VIDEO'

export const DELETE_GALERIE = 'DELETE_GALERIE'
export const FETCH_GALERIE = 'FETCH_GALERIE'
export const ADAUGA_GALERIE = 'ADAUGA_GALERIE'

export const DELETE_GALERIEVIDEO = 'DELETE_GALERIEVIDEO'
export const FETCH_GALERIEVIDEO = 'FETCH_GALERIEVIDEO'
export const ADAUGA_GALERIEVIDEO ='ADAUGA_GALERIEVIDEO'

export const SCHIMBA_DIMENSIUNI ='SCHIMBA_DIMENSIUNI'

export const DELETE_GALERIEVIDEOEVENIMENTE = 'DELETE_GALERIEVIDEOEVENIMENTE'
export const FETCH_GALERIEVIDEOEVENIMENTE = 'FETCH_GALERIEVIDEOEVENIMENTE'
export const ADAUGA_GALERIEVIDEOEVENIMENTE ='ADAUGA_GALERIEVIDEOEVENIMENTE'

export const STERGE_EROARE ="STERGE_EROARE"